# These settings affect the whole site.

# For setting changed often, consider using Jekyll's data files feature.
# Restart the server process after changing this file.
# Access site variables via {{ site.title }}, {{ site.email }}, and so on.
# Description appears in document head meta (for Google search results)
# and in feed.xml site description.
# Use a variable: >  to ignore new lines until the next variable
# Be careful with http vs https; wrong one may cause CSS loading error

title: Leigh Henderson's Laboratory
# email: your-email@domain.com
description: Welcome to academic biomedical research. Here's your introduction to the protocols used in university laboratories the world over, with emphasis on basic concepts underlying common protocols. 

baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://LeighHenderson.github.io"
url: "http://localhost:4000" # Use this for development with  "jekyll serve"

repository: LeighHenderson/LeighHenderson.github.io
# twitter_username: jekyllrb
github_username: LeighHenderson

logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Custom pages will be organized into the _pages directory
include: ['_pages']

# Exclude Gulp workflow from Jekyll processing
exclude: [
    "_dev",
    "gulpfile.js",
    "node_modules",
    "package.json",
    "npm-debug.log"
]

# theme: minima

defaults:
    -
        values:
            layout: default
